stages:
    - packer
    - versioning
    - terraform
    - upload_vmware

packer_create:
    stage: packer
    tags:
        - windows
    script:
        - packer init .
        - packer validate .
        - packer build -force .
        #- echo "skip"


clone_VM:
    stage: versioning
    tags:
        - windows
    before_script:
        - chmod +x Upload_VMware/versioning_VM.sh
        - export GOVC_PASSWORD=$(echo $GOVC_PASSWORD_BASE64 | base64 --decode)
        - govc session.login -k=true -u $GOVC_USERNAME:$GOVC_PASSWORD@$GOVC_URL
    script:
        - Upload_VMware/versioning_VM.sh
    after_script:
        - govc session.logout
    artifacts:
        paths:
            - variables.txt

versioning_template_5:
    stage: versioning
    tags:
        - linux
    script:
        - pwsh -ExecutionPolicy Bypass -File Versioning/versioning_5.ps1
    
terraform_create:
    stage: terraform
    tags:
        - windows
    script:
        - terraform -chdir=Terraform init
        - terraform -chdir=Terraform plan 
        - terraform -chdir=Terraform apply -auto-approve
    artifacts:
        untracked: yes
        expose_as: "terraform"
        paths:
            - Terraform


terraform_destroy_valid:
    stage: terraform
    tags:
        - windows
    when: manual
    needs: 
        - terraform_create
    script:
        - terraform -chdir=Terraform destroy -auto-approve
    dependencies:
        - terraform_create


terraform_destroy_invalid:
    stage: terraform
    tags:
        - windows
    when: manual
    needs: 
        - terraform_create
    script:
        - terraform -chdir=Terraform destroy -auto-approve
        - echo "Template non valido"; exit 78
    dependencies:
        - terraform_create
    allow_failure: false


upload_content-library:
    stage: upload_vmware
    tags:
        - windows
    needs:
        - terraform_destroy_valid
        - job: clone_VM
          artifacts: true
    before_script:
        - source variables.txt
        - chmod +x Upload_VMware/upload_vcenter.sh
        - export GOVC_PASSWORD=$(echo $GOVC_PASSWORD_BASE64 | base64 --decode)
        - govc session.login
    script:
        - govc library.rm $CL_DEPLOY_TEMPLATE"/"$VC_TEMPLATE_NAME
        - govc vm.clone -on=False -vm $VM_VERSIONED -folder="$VC_VM_TEMPLATE_MOVE_FOLDER" -ds=$DATASTORE_TARGET $VC_VM_EPHEMERAL
        - govc library.clone -vm $VC_VM_EPHEMERAL -ds $DATASTORE_TARGET -cluster=$VC_CLUSTER_NAME $CL_DEPLOY_TEMPLATE $VC_TEMPLATE_NAME
        - govc vm.destroy $VC_VM_EPHEMERAL        
    after_script:
        - govc session.logout
    dependencies:
        - terraform_destroy_valid
        - clone_VM


generate_branch:
    stage: upload_vmware
    tags:
        - windows
    needs:
        - clone_VM
        - upload_content-library
    script:
        - git config --global user.email "service@gitlab_pipeline.com"
        - git config --global user.name "service_repository_pipeline"
        - git fetch
        - git checkout -b $VC_VM_NAME origin/main
        - echo "Template di riferimento:" > template_version.txt
        - echo "ver. "$VC_VM_NAME >> template_version.txt
        - git add template_version.txt
        - git commit -m "Aggiunto file versioning"
        - git push origin https://$GITLAB_USER:$GITLAB_TOKEN@$CI_REPOSITORY_URL $VC_VM_NAME
    dependencies:
        - upload_content-library
    only: 
        - main
